sudo: false
language: java
dist: trusty
jdk:
- oraclejdk11
- openjdk11
install:
- mvn -v
- mvn -B install -U -DskipTests=true
after_success:
- tools/deploy_snapshots.sh
cache:
  directories:
  - "${HOME}/.m2"
branches:
  only:
  - master
env:
  global:
  - secure: Cgnhp3Bbz8cKyOxgxpPACOw32zrL8Svs6798ApfIgT+8LBdRPSJyEDXP/k3NLzBJPFgKRhIia7tlzpCPNd45I7+jUSSc5cH6aXmd+WIafyu3Eqb9qkgDaPVWHRqpv0tvC8gATAiRqbrDrNwubJ5NXctqxHkoprrAUMRQ8MmdO7CTECiRRWh0xWagOwQ+xkdbvYCoKkH7yJeYR3zF09WkcBQY5GA8I3j7WaeiCcoKcIiW8S2x7Eegjv6q3e3f2mQ0LIp3hVnkLMB0CiUuIKFtIh1/VBvfFii5wi2NvKzo8mYS65u6YWjBkq5SiKB9+Fxi102KKy+SLEancHCA7+kU3XyRjsoYaJjRaAY4XROvEMKJrgIfIvuFyrCFHYax+X/qq3nrGqQUNGuI9dttAnKzn9q+5zLkEXbWqNxDDiAkfcGZ+qyvb2AbEOR+FxT5WV2dUIwXbPfvI54Lz55nel975h45Pp0toasTGrnJhWg6N7Yv6iKyV+M0cKqwvCikXTPRwBJz6OD1MIrgf2W6eeuWUqTojREQoN1kiK4IpZUSIl4QyTrrFuCE6HzZj7jdi4dpOJOpDA5e6XoeM0EVPrhxuem7IH6nZ0m3xp5uq3J/jbioZl13wzND2ooLICeqy9HV+G6fFkBRuPXrqF9LTICMdihzuUa9eVfCUxyP8ZAPlqY=
  - secure: nZZ/o90RmJJHTl7ueHrWwZjmu7KBFcLdtHIL86JhYxTPaMMxg6YwpUhQ3Yb1jcsQxMBDZmlzzv5pz5FGrQ+xOodOkW0PKCG/VLBa8vFCi5Q3Xvsz3o6rsKgM/v4tCYpxoSLr5Gao9V0QujhWxFKO1gbhpF197aFChjdZM2D7+S2ux2TRtxqsqsEYc6GU8xZrlMG/zYP4M/2pFkjiNGV15bvtCeKf9edwoCz/2UcMO3zA5L60EHjL62qACZGmdfUR7v8GihaX7oorQnQL7qIDXVat04qrq4gItHKleQx93FS+TK83/Dq+62JtrX36+Is5Pth5nQ6qlZnIsPzSPAQwJxut7FrM9jHwA96OgOh43KAk7kUAfrZ2epmBuOhk3coOSQ1namKUECB6WkuCWgAsAD9Td6/DmFuc6F0uC+/qp+TSZRsGe0xtvGK5B8pXS1a1bUixhCjxp+0nxjcls5C1i2ytCfJ7db2kHkYvuAMfeX6rx80kDandj/aPfHAbe7om7c/AfJSQRAq1v3W9YWYBmKQBzYGhUWlyJhNsa5DQkMAaqGnhLts2bKHdHbAQAeqYFB2EtYFgzTPwzZlcVxaxQdDYFg7JynyD0anuL1Y58t57cGACWDugZsKl+UySrf19M2CSZsavoOE0Eyr1WDuAJyb2sSGRrySPpeHboAPQMI0=
