sudo: false
language: java
dist: trusty
jdk:
- oraclejdk11
- openjdk11
install:
- mvn -v
- mvn -B install -U -DskipTests=true
#after_success:
#- tools/deploy_snapshots.sh
cache:
  directories:
  - "${HOME}/.m2"
branches:
  only:
  - master
